#!/bin/bash
echo "connecting flatpak to flathub if it is not already connected"
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
echo "installing programs "
flatpak install flathub org.vinegarhq.Sober
flatpak install flathub xyz.z3ntu.razergenie
flatpak install flathub org.DolphinEmu.dolphin-emu
flatpak install flathub com.steamgriddb.SGDBoop
flatpak install flathub io.github.philipk.boilr
echo "done"
