set $mon1 HDMI-A-0
set $mon2 DisplayPort-2
exec --no-startup-id  xrandr   --output HDMI-A-0 --primary --mode 1920x1080 --rate 165 --pos 0x0 --scale 1x1  --output DisplayPort-2 --mode 1920x1080 --rate 60 --pos 1920x405 --right-of HDMI-A-0
bindsym $mod+r kill #test to see if it reads it which it does mod+r does indeed work

#YOU NEED THIS LINE
include ~/.config/home-manager/home/i3/workspaces

